# Generated by Django 3.1.7 on 2021-04-06 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFolder',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('userFullname', models.CharField(max_length=50)),
                ('folderName', models.CharField(max_length=100, unique=True)),
                ('folderCreatedTime', models.DateTimeField()),
                ('public', models.BooleanField(default=True, verbose_name='public')),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddBookmark',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarkLabel', models.CharField(max_length=100)),
                ('bookmarkTitle', models.CharField(max_length=300)),
                ('bookmarkUrl', models.URLField()),
                ('folderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopApp.addfolder')),
            ],
        ),
    ]
