# Generated by Django 3.1.7 on 2021-05-13 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbookmark',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
