# Generated by Django 3.1.7 on 2021-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopApp', '0002_addbookmark_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbookmark',
            name='favourite',
        ),
        migrations.AddField(
            model_name='addbookmark',
            name='fav',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
